export const UPDATE_EMAIL = 'SIGNIN_MUTATION_UPDATE_EMAIL'
export const UPDATE_PASSWORD = 'SIGNIN_MUTATION_UPDATE_PASSWORD'
export const LAST_SIGNIN_STATUS = 'SIGNIN_MUTATION_LAST_LOGIN_STATUS'
export const CLEAR_STATE = 'SIGNIN_MUTATION_CLEAR_STATE'
