export const UPDATE_EMAIL = 'SIGNIN_ACTION_UPDATE_EMAIL'
export const UPDATE_PASSWORD = 'SIGNIN_ACTION_UPDATE_PASSWORD'
export const PERFORM_SIGNIN = 'SIGNIN_ACTION_PERFORM_LOGIN'
export const CLEAR_STATE = 'SIGNIN_ACTION_CLEAR_STATE'
