export const LOAD_MESSAGE = 'MESSAGE_MUTATION_LOAD_MESSAGE'
export const LOAD_OTHER_USER = 'MESSAGE_MUTATION_LOAD_OTHER_USER'
export const SAVE_MESSAGE = 'MESSAGE_MUTATION_SAVE_MESSAGE'
export const CLEAR_STATE = 'MESSAGE_MUTATION_CLEAR_STATE'
