export const PERFORM_LOAD_MESSAGE = 'MESSAGE_ACTION_LOAD_MESSAGE'
export const PERFORM_LOAD_OTHER_USER = 'MESSAGE_ACTION_LOAD_OTHER_USER'
export const PERFORM_SAVE_MESSAGE = 'MESSAGE_ACTION_SAVE_MESSAGE'
export const CLEAR_STATE = 'MESSAGE_ACTION_CLEAR_STATE'
