export const LOAD_SERVICES = 'SERVICES_MUTATION_LOAD_SERVICES'
export const LOAD_SERVICE_PROVIDERS = 'SERVICES_MUTATION_LOAD_SERVICE_PROVIDERS'
export const LOAD_SERVICE_PROVIDERS_BY_ID = 'SERVICES_MUTATION_LOAD_SERVICE_PROVIDERS_BY_ID'
export const CLEAR_STATE = 'SERVICES_MUTATION_CLEAR_STATE'
